// <auto-generated />
using System;
using DmarcAnalyzer.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DmarcAnalyzer.Api.Data.Migrations
{
    [DbContext(typeof(DmarcAnalyzerDbContext))]
    [Migration("20260812080817_AddMachineCredentialsAndIngestReceipts")]
    partial class AddMachineCredentialsAndIngestReceipts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.AgencyUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("agency_user", (string)null);
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.AlertEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DomainId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("NotifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAtUtc");

                    b.HasIndex("DomainId");

                    b.HasIndex("ClientId", "RuleType", "DetectedAtUtc");

                    b.ToTable("alert_event", (string)null);
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.ApiCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("LastUsedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ReportSourceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TokenId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ReportSourceId");

                    b.HasIndex("TokenId")
                        .IsUnique();

                    b.ToTable("api_credential", (string)null);
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClientName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Details")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetType")
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("ClientId", "OccurredAtUtc");

                    b.HasIndex("EventType", "OccurredAtUtc");

                    b.ToTable("audit_event", (string)null);
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.BackupStreamState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime?>("LastSuccessAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Stream")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("WatermarkUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Stream")
                        .IsUnique();

                    b.ToTable("backup_stream_state", (string)null);
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AlertComplianceDropPercent")
                        .HasColumnType("integer");

                    b.Property<int?>("AlertMinMessages")
                        .HasColumnType("integer");

                    b.Property<bool>("AlertsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("LegalHold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("RetentionMonths")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("client", (string)null);
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.DigestDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PeriodEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PeriodStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RecipientCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId", "PeriodStartUtc")
                        .IsUnique();

                    b.ToTable("digest_delivery", (string)null);
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.DmarcReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DkimAlignment")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("relaxed");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("IngestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("PublishedPct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100);

                    b.Property<string>("PublishedPolicy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("none");

                    b.Property<DateTime>("RangeBeginUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RangeEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RecordCount")
                        .HasColumnType("integer");

                    b.Property<string>("ReportId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("ReportSourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("SpfAlignment")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("relaxed");

                    b.Property<string>("SubdomainPolicy")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("DomainId");

                    b.HasIndex("ReportSourceId");

                    b.HasIndex("DomainId", "ReportId", "RangeBeginUtc", "RangeEndUtc")
                        .IsUnique();

                    b.ToTable("dmarc_report", (string)null);
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.DmarcReportIngest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("IngestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PolicyDomain")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("RecordCount")
                        .HasColumnType("integer");

                    b.Property<string>("ReportId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("ReportRangeBeginUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ReportRangeEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReportSourceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ReportSourceId");

                    b.HasIndex("ClientId", "PolicyDomain", "ReportId", "ReportRangeBeginUtc", "ReportRangeEndUtc")
                        .IsUnique();

                    b.ToTable("dmarc_report_ingest", (string)null);
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.DmarcReportRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Disposition")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("DkimResult")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("DmarcReportId")
                        .HasColumnType("uuid");

                    b.Property<string>("EnvelopeFrom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("EnvelopeTo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("HeaderFrom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("MessageCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReportRangeBeginUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceIp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SpfResult")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("DmarcReportId");

                    b.HasIndex("ReportRangeBeginUtc");

                    b.ToTable("dmarc_report_record", (string)null);
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.DmarcReportRecordDkimAuthResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DmarcReportRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("HumanResult")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Selector")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("DmarcReportRecordId");

                    b.ToTable("dmarc_report_record_dkim_auth_result", (string)null);
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.DmarcReportRecordSpfAuthResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DmarcReportRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("HumanResult")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("DmarcReportRecordId");

                    b.ToTable("dmarc_report_record_spf_auth_result", (string)null);
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.Domain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DnsCheckedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DnsLookupStatus")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("DnsPolicy")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("DnsPolicyInheritedFrom")
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("DnsCheckedAtUtc");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("domain", (string)null);
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.MailboxSyncRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttachmentsProcessed")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MessagesScanned")
                        .HasColumnType("integer");

                    b.Property<int>("ParseFailures")
                        .HasColumnType("integer");

                    b.Property<Guid>("ReportSourceId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReportsInserted")
                        .HasColumnType("integer");

                    b.Property<int>("ReportsSkippedAsDuplicate")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("TlsReportsInserted")
                        .HasColumnType("integer");

                    b.Property<int>("TlsReportsSkippedAsDuplicate")
                        .HasColumnType("integer");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("ReportSourceId")
                        .HasDatabaseName("IX_mailbox_sync_run_ReportSourceId");

                    b.HasIndex("StartedAtUtc");

                    b.ToTable("mailbox_sync_run", (string)null);
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.MtaStsPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("MaxAgeSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("ModeChangedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MxPatterns")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("PolicyId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DomainId")
                        .IsUnique();

                    b.ToTable("mta_sts_policy", (string)null);
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.MtaStsState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DnsRecordStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uuid");

                    b.Property<string>("FetchDetail")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("FetchStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("IssuesJson")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastChangedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastCheckedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastFetchOkAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("MaxAgeSeconds")
                        .HasColumnType("bigint");

                    b.Property<string>("Mode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("MxHostsJson")
                        .HasColumnType("text");

                    b.Property<string>("MxLookupStatus")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("PolicyBody")
                        .HasColumnType("text");

                    b.Property<string>("PolicyId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("PolicyIdChangedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("PolicyValid")
                        .HasColumnType("boolean");

                    b.Property<string>("PreviousPolicyId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RawRecord")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("UnmatchedMxHostsJson")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DomainId")
                        .IsUnique();

                    b.HasIndex("LastCheckedAtUtc");

                    b.ToTable("mta_sts_state", (string)null);
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.NotificationRecipient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Kind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("both");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ClientId", "Email")
                        .IsUnique();

                    b.ToTable("notification_recipient", (string)null);
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.ReportIngestReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("PayloadCount")
                        .HasColumnType("integer");

                    b.Property<string>("PayloadSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReportSourceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReceivedAtUtc");

                    b.HasIndex("ReportSourceId", "PayloadSha256")
                        .IsUnique();

                    b.ToTable("report_ingest_receipt", (string)null);
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.ReportSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DefaultClientId")
                        .HasColumnType("uuid");

                    b.Property<bool>("DeleteAfterRetention")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<long?>("LastProcessedUid")
                        .HasColumnType("bigint");

                    b.Property<long?>("LastProcessedUidValidity")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastSuccessSyncAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("OldestMessageAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordEncrypted")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("UseTls")
                        .HasColumnType("boolean");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("DefaultClientId");

                    b.ToTable("report_source", (string)null);
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.SmtpTlsFailureDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalInformation")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<long>("FailedSessionCount")
                        .HasColumnType("bigint");

                    b.Property<string>("FailureCategory")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("FailureReasonCode")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ReceivingIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ReceivingMxHelo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ReceivingMxHostname")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ResultType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SendingMtaIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("SmtpTlsReportPolicyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SmtpTlsReportPolicyId");

                    b.ToTable("smtp_tls_failure_detail", (string)null);
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.SmtpTlsReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContactInfo")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTime>("IngestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("PolicyCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RangeBeginUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RangeEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReportId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("ReportSourceId")
                        .HasColumnType("uuid");

                    b.Property<long>("TotalFailureSessionCount")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalSuccessfulSessionCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RangeEndUtc");

                    b.HasIndex("ReportSourceId");

                    b.HasIndex("OrganizationName", "ReportId", "RangeBeginUtc", "RangeEndUtc")
                        .IsUnique();

                    b.ToTable("smtp_tls_report", (string)null);
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.SmtpTlsReportPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uuid");

                    b.Property<long>("FailureSessionCount")
                        .HasColumnType("bigint");

                    b.Property<string>("MxHostPatterns")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("PolicyDomain")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PolicyString")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("PolicyType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("ReportRangeBeginUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ReportRangeEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SmtpTlsReportId")
                        .HasColumnType("uuid");

                    b.Property<long>("SuccessfulSessionCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ReportRangeEndUtc");

                    b.HasIndex("SmtpTlsReportId");

                    b.HasIndex("DomainId", "ReportRangeBeginUtc");

                    b.ToTable("smtp_tls_report_policy", (string)null);
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.TlsReportIngest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContactInfo")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTime>("IngestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("PolicyCount")
                        .HasColumnType("integer");

                    b.Property<string>("PolicyDomains")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ReportId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("ReportRangeBeginUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ReportRangeEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReportSourceId")
                        .HasColumnType("uuid");

                    b.Property<long>("TotalFailureSessionCount")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalSuccessfulSessionCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ReportRangeEndUtc");

                    b.HasIndex("ReportSourceId");

                    b.HasIndex("ClientId", "OrganizationName", "ReportId", "ReportRangeBeginUtc", "ReportRangeEndUtc")
                        .IsUnique();

                    b.ToTable("tls_report_ingest", (string)null);
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.UserClientGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("UserId", "ClientId")
                        .IsUnique();

                    b.ToTable("user_client_grant", (string)null);
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.UserIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailAtLink")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Issuer", "Subject")
                        .IsUnique();

                    b.ToTable("user_identity", (string)null);
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CookieId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CookieId")
                        .IsUnique();

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("UserId");

                    b.ToTable("user_session", (string)null);
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.AlertEvent", b =>
                {
                    b.HasOne("DmarcAnalyzer.Api.Data.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DmarcAnalyzer.Api.Data.Entities.Domain", "Domain")
                        .WithMany()
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");

                    b.Navigation("Domain");
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.ApiCredential", b =>
                {
                    b.HasOne("DmarcAnalyzer.Api.Data.Entities.ReportSource", "ReportSource")
                        .WithMany()
                        .HasForeignKey("ReportSourceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ReportSource");
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.DigestDelivery", b =>
                {
                    b.HasOne("DmarcAnalyzer.Api.Data.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.DmarcReport", b =>
                {
                    b.HasOne("DmarcAnalyzer.Api.Data.Entities.Domain", "Domain")
                        .WithMany()
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DmarcAnalyzer.Api.Data.Entities.ReportSource", "ReportSource")
                        .WithMany()
                        .HasForeignKey("ReportSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Domain");

                    b.Navigation("ReportSource");
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.DmarcReportIngest", b =>
                {
                    b.HasOne("DmarcAnalyzer.Api.Data.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DmarcAnalyzer.Api.Data.Entities.ReportSource", "ReportSource")
                        .WithMany()
                        .HasForeignKey("ReportSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("ReportSource");
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.DmarcReportRecord", b =>
                {
                    b.HasOne("DmarcAnalyzer.Api.Data.Entities.DmarcReport", "DmarcReport")
                        .WithMany("Records")
                        .HasForeignKey("DmarcReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DmarcReport");
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.DmarcReportRecordDkimAuthResult", b =>
                {
                    b.HasOne("DmarcAnalyzer.Api.Data.Entities.DmarcReportRecord", "DmarcReportRecord")
                        .WithMany("DkimAuthResults")
                        .HasForeignKey("DmarcReportRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DmarcReportRecord");
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.DmarcReportRecordSpfAuthResult", b =>
                {
                    b.HasOne("DmarcAnalyzer.Api.Data.Entities.DmarcReportRecord", "DmarcReportRecord")
                        .WithMany("SpfAuthResults")
                        .HasForeignKey("DmarcReportRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DmarcReportRecord");
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.Domain", b =>
                {
                    b.HasOne("DmarcAnalyzer.Api.Data.Entities.Client", "Client")
                        .WithMany("Domains")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.MailboxSyncRun", b =>
                {
                    b.HasOne("DmarcAnalyzer.Api.Data.Entities.ReportSource", "ReportSource")
                        .WithMany()
                        .HasForeignKey("ReportSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReportSource");
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.MtaStsPolicy", b =>
                {
                    b.HasOne("DmarcAnalyzer.Api.Data.Entities.Domain", "Domain")
                        .WithMany()
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domain");
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.MtaStsState", b =>
                {
                    b.HasOne("DmarcAnalyzer.Api.Data.Entities.Domain", "Domain")
                        .WithMany()
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domain");
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.NotificationRecipient", b =>
                {
                    b.HasOne("DmarcAnalyzer.Api.Data.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Client");
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.ReportIngestReceipt", b =>
                {
                    b.HasOne("DmarcAnalyzer.Api.Data.Entities.ReportSource", "ReportSource")
                        .WithMany()
                        .HasForeignKey("ReportSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportSource");
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.ReportSource", b =>
                {
                    b.HasOne("DmarcAnalyzer.Api.Data.Entities.Client", "DefaultClient")
                        .WithMany()
                        .HasForeignKey("DefaultClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DefaultClient");
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.SmtpTlsFailureDetail", b =>
                {
                    b.HasOne("DmarcAnalyzer.Api.Data.Entities.SmtpTlsReportPolicy", "Policy")
                        .WithMany("FailureDetails")
                        .HasForeignKey("SmtpTlsReportPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.SmtpTlsReport", b =>
                {
                    b.HasOne("DmarcAnalyzer.Api.Data.Entities.ReportSource", "ReportSource")
                        .WithMany()
                        .HasForeignKey("ReportSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReportSource");
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.SmtpTlsReportPolicy", b =>
                {
                    b.HasOne("DmarcAnalyzer.Api.Data.Entities.Domain", "Domain")
                        .WithMany()
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DmarcAnalyzer.Api.Data.Entities.SmtpTlsReport", "Report")
                        .WithMany("Policies")
                        .HasForeignKey("SmtpTlsReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domain");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.TlsReportIngest", b =>
                {
                    b.HasOne("DmarcAnalyzer.Api.Data.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DmarcAnalyzer.Api.Data.Entities.ReportSource", "ReportSource")
                        .WithMany()
                        .HasForeignKey("ReportSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("ReportSource");
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.UserClientGrant", b =>
                {
                    b.HasOne("DmarcAnalyzer.Api.Data.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DmarcAnalyzer.Api.Data.Entities.AgencyUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DmarcAnalyzer.Api.Data.Entities.AgencyUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("CreatedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.UserIdentity", b =>
                {
                    b.HasOne("DmarcAnalyzer.Api.Data.Entities.AgencyUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.UserSession", b =>
                {
                    b.HasOne("DmarcAnalyzer.Api.Data.Entities.AgencyUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.Client", b =>
                {
                    b.Navigation("Domains");
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.DmarcReport", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.DmarcReportRecord", b =>
                {
                    b.Navigation("DkimAuthResults");

                    b.Navigation("SpfAuthResults");
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.SmtpTlsReport", b =>
                {
                    b.Navigation("Policies");
                });

            modelBuilder.Entity("DmarcAnalyzer.Api.Data.Entities.SmtpTlsReportPolicy", b =>
                {
                    b.Navigation("FailureDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
